// To FitBit
export const UPDATE_UI = 'UPDATE_UI';

// To Companion
export const LIGHTS_UPDATE_GROUPLIST = 'LIGHTS_UPDATE_GROUPLIST';
export const LIGHTS_GROUP_ON = 'LIGHTS_GROUP_ON';
export const LIGHTS_GROUP_OFF = 'LIGHTS_GROUP_OFF';

export const THERMOSTAT_UPDATE_ZONESLIST = 'THERMOSTAT_UPDATE_ZONESLIST';
export const THERMOSTAT_SET_TEMPERATURE = 'THERMOSTAT_SET_TEMPERATURE';

export const SOLAR_UPDATE_OUTPUTSLIST = 'SOLAR_UPDATE_OUTPUTSLIST';

export const CAR_UPDATE_CHARGE = 'CAR_UPDATE_CHARGE';